# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170206_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 6, 15, 36, 15, 11430, tzinfo=utc)),
        ),
    ]
