# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postagens_data_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 3, 1, 39, 273350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='imagem',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
