# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170209_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 19, 40, 49, 555258, tzinfo=utc)),
        ),
    ]
