# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170209_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_carosel', models.CharField(max_length=50)),
                ('texto_carosel', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 19, 47, 13, 425987, tzinfo=utc)),
        ),
    ]
