# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170210_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enviados',
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 13, 27, 21, 942896, tzinfo=utc)),
        ),
    ]
