# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170218_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meu_From',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 14, 8, 48, 841478, tzinfo=utc)),
        ),
    ]
