# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170218_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meu_From',
            new_name='formss',
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 14, 9, 58, 117458, tzinfo=utc)),
        ),
    ]
