# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170218_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formss',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formss',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 15, 26, 56, 208457, tzinfo=utc)),
        ),
    ]
